// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiFrdlJKGum9lYEuqATYxQD4dOcKuTHWw',
    appId: '1:419609452716:web:e464099c911342e56aff09',
    messagingSenderId: '419609452716',
    projectId: 'madb1-633fc',
    authDomain: 'madb1-633fc.firebaseapp.com',
    storageBucket: 'madb1-633fc.appspot.com',
    measurementId: 'G-TJ500C0KCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpPPVCsoM1OZBj76t8uVPN1Wq8hjMB4sU',
    appId: '1:419609452716:android:a0432fa0ce05208e6aff09',
    messagingSenderId: '419609452716',
    projectId: 'madb1-633fc',
    storageBucket: 'madb1-633fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi5eJ2AJV1mBKFQxgRoBcOJsZLAjHF-3Y',
    appId: '1:419609452716:ios:eba1486ce9e97c676aff09',
    messagingSenderId: '419609452716',
    projectId: 'madb1-633fc',
    storageBucket: 'madb1-633fc.appspot.com',
    iosBundleId: 'com.example.flutterfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi5eJ2AJV1mBKFQxgRoBcOJsZLAjHF-3Y',
    appId: '1:419609452716:ios:1c22e24285df15dd6aff09',
    messagingSenderId: '419609452716',
    projectId: 'madb1-633fc',
    storageBucket: 'madb1-633fc.appspot.com',
    iosBundleId: 'com.example.flutterfirebase.RunnerTests',
  );
}
